services:
  - type: web
    name: zathu-backend
    env: php
    region: oregon
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000"
    plan: starter
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PAYCHANGU_PUBLIC_KEY
        sync: false
      - key: PAYCHANGU_SECRET_KEY
        sync: false
